/** Crawlable sourcing guidance, kept below the focused collection experience. */
export function SourcingEvidence() {
  return <div className="reference-evidence">
    <section><h3>What the catalogue confirms</h3><p>Each public record identifies a finished-fabric article and its documented composition, GSM, usable width and series. These facts help a buyer shortlist a construction before requesting a sample. Article names describe a sourcing direction; they do not establish stock, colour, price, lead time or a certified performance result.</p></section>
    <section><h3>What still requires sample approval</h3><p>Hand feel, colour, surface finish, stretch, recovery and garment performance depend on the approved sample and intended processing route. They are not inferred from an article name alone. Confirm whether weight and width refer to the finished, relaxed condition and whether the requested colour or finish changes those measurements.</p></section>
    <section><h3>What makes an RFQ actionable</h3><p>Send the closest article number with garment use, target specification, colour, quantity, destination and testing requirements. Sales can then confirm sampling, live availability and commercial terms. If a field is unconfirmed in the catalogue, keep it as a confirmation request instead of treating a missing number as a specification.</p></section>
    <section><h3>How to shortlist a finished knit fabric</h3><p>Begin with garment behaviour: define the garment type, silhouette, season, target hand feel and care route before comparing fibre percentages. A close-fitting top may prioritise stretch, recovery and opacity, while a hoodie may prioritise body, warmth, surface character and seam behaviour.</p><p>The same composition can perform differently when yarn, knit construction, density and finishing change. Compare article number, composition, GSM and usable width under the same conditions, then review surface appearance, drape, shrinkage, pilling and colourfastness against the intended market.</p></section>
    <section><h3>Build an approval record</h3><p>Keep the selected article number together with the approved colour, finish, measured GSM, usable width, test requirements and sample date. Add the intended order quantity, delivery destination and documentation needs before requesting final commercial confirmation.</p><p>If a requirement changes, identify the changed field and retain the superseded value. This gives sampling and bulk discussions an evidence trail to the correct revision; the approved sample establishes the working standard.</p></section>
  </div>;
}
